#!/bin/bash

## Copyright 2018 Jack Green (ja-green)
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.

## promptly
## easy to use, component based library for customising your bash prompt
##
## examples:
## edit your prompt:
##     $ prommptly edit -e vim
##
## show what your current prompt would look like:
##     $ promptly show
##
## list available components:
##     $ promptly help components
##
## get help with a specific component:
##     $ promptly help git_status
##

[[ ${#} -eq 0 ]] && cmd="help"

main() {
  args="${@}"

  while [ -n "${1}" ]; do
    case "${1}" in
      --) shift; break ;;
      -*) case "${1}" in
      -v|--version)   cmd="version"; unset args ;;
      -h|--help)      cmd="help";    unset args ;;
    esac ;;

       *) [ -z "${cmd}" ] && cmd="${1}" ;;

    esac
    shift

  done

  if [ -f "${PROMPTLY_HOME}/builtin/promptly-${cmd}" ]; then
    "${PROMPTLY_HOME}/builtin/promptly-${cmd}" "${args}"
  elif type "promptly-${cmd}" &>/dev/null; then
     "promptly-${cmd}" "${args}"
  else 
     die "fatal: '%s' is not a promptly command. \n\nsee 'promptly help -a'\n"
  fi
}

main "${@}"

exit ${?}

